# Generated by Django 4.2.2 on 2023-06-10 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('product_gender', models.CharField(choices=[('Men', 'Men'), ('Women', 'Women')], default='Men', max_length=10)),
                ('product_type', models.CharField(max_length=30)),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('product_brand', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='Products.brand')),
                ('product_category', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='Products.category')),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Variants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.ManyToManyField(to='Products.color')),
                ('size', models.ForeignKey(default=False, on_delete=django.db.models.deletion.RESTRICT, to='Products.size')),
                ('variant_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='Products.products')),
            ],
        ),
        migrations.AddField(
            model_name='products',
            name='product_sport',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='Products.sport'),
        ),
    ]
