# Generated by Django 4.2.2 on 2023-06-11 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_variants_stock_variants_variant_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variants',
            name='color',
        ),
        migrations.AddField(
            model_name='variants',
            name='color',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.RESTRICT, to='Products.color'),
        ),
    ]
