# Generated by Django 4.2.2 on 2023-06-15 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0003_remove_variants_color_variants_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='color_code',
            field=models.CharField(default='#FF0000', max_length=7),
            preserve_default=False,
        ),
    ]
