# Generated by Django 4.2.2 on 2023-06-26 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0006_category1_product1_variation_colorvariation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colorvariation',
            name='variation',
        ),
        migrations.RemoveField(
            model_name='product1',
            name='category',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='variation',
        ),
        migrations.RemoveField(
            model_name='seriesvariation',
            name='variation',
        ),
        migrations.RemoveField(
            model_name='sizevariation',
            name='variation',
        ),
        migrations.RemoveField(
            model_name='storagevariation',
            name='variation',
        ),
        migrations.RemoveField(
            model_name='stylevariation',
            name='variation',
        ),
        migrations.RemoveField(
            model_name='variation',
            name='product',
        ),
        migrations.DeleteModel(
            name='Category1',
        ),
        migrations.DeleteModel(
            name='ColorVariation',
        ),
        migrations.DeleteModel(
            name='Product1',
        ),
        migrations.DeleteModel(
            name='ProductVariant',
        ),
        migrations.DeleteModel(
            name='SeriesVariation',
        ),
        migrations.DeleteModel(
            name='SizeVariation',
        ),
        migrations.DeleteModel(
            name='StorageVariation',
        ),
        migrations.DeleteModel(
            name='StyleVariation',
        ),
        migrations.DeleteModel(
            name='Variation',
        ),
    ]
